# Generated by Django 2.1 on 2021-03-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0004_userinfo_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='country',
            new_name='xxx',
        ),
    ]
