# Generated by Django 2.1 on 2021-03-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0005_auto_20210311_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='xxx',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32),
        ),
    ]
