# Generated by Django 2.1 on 2021-03-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0007_auto_20210311_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32),
        ),
    ]
