# Generated by Django 2.1.1 on 2021-03-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0011_userinfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='country',
        ),
    ]
