# Generated by Django 2.1.1 on 2021-03-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0013_auto_20210311_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('age', models.CharField(max_length=32, null=True)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('country', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
