# Generated by Django 2.1.1 on 2021-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0014_userinfoall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfoAll',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
