# Generated by Django 2.1.1 on 2021-03-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0015_auto_20210312_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
    ]
