# Generated by Django 2.2.6 on 2021-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0016_auto_20210312_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creat_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
